# Generated by Django 5.2.17 on 2026-10-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('job_description', models.TextField()),
                ('resume_text', models.TextField()),
                ('match_percentage', models.FloatField()),
                ('matched_skills', models.TextField()),
                ('missing_skills', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
