# Generated by Django 5.2.17 on 2026-10-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='match_percentage',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='resume',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='matched_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='missing_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
    ]
